apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: raft-operator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - infra.hugo.dev
  resources:
  - raftclusters
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - infra.hugo.dev
  resources:
  - raftclusters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - infra.hugo.dev
  resources:
  - raftclusters/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raft-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: raft-operator
subjects:
- kind: ServiceAccount
  name: raft-operator
  namespace: default

